camera:
  client: GEOPARK
  coordinates:
    area1:
      A_Person: '10'
      camara: Afuera
      points:
      - x: 4.651525550633306
        y: 1.1822089947089947
      - x: 295.760279528296
        y: 2.769510582010582
      - x: 297.8567417482997
        y: 147.213955026455
      - x: 7.047482373494727
        y: 144.03935185185185
      punto: TORITO_OESTE1_GEOPARK
  info_emails: '["cristian.tascon@axuretechnologies.com"]'
  info_notifications: '{"Email":true, "Imagen": true, "Page_HSE": true, "Video": false,
    "Whatsap":true}'
  info_numeros: '["+573144599019","+573012874982"]'
  ip: 172.30.37.15
  label: Green, No_Harness, No_Helmet, Harness, Yellow, A_Person, White
  name camera: Afuera
  password: 4xUR3_2017
  place: Pozo1
  point: TORITO_OESTE1_GEOPARK
  port: 554
  rtsp_url: VideosEnsayoModelo/muchas-personas-perimetral2.mp4
  time_areas: '{"area1": "3", "area2": "5", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/best.pt
